import os.path
import unittest

import pandas as pd
from pkg_resources import resource_filename
from tqdm import tqdm
from wcvp_download import wcvp_accepted_columns, get_all_taxa
from wcvp_name_matching import get_accepted_info_from_names_in_column

from knapsack_searches import get_metabolites_for_taxon, get_metabolites_in_family, kn_metabolite_name_column
from metabolite_properties import get_N_containing_from_metabolites, get_alkaloids_from_metabolites

input_test_dir = resource_filename(__name__, 'test_inputs')
test_output_dir = resource_filename(__name__, 'test_outputs')


class MyTestCase(unittest.TestCase):

    def taxon_test(self, name, known_vals):
        table = get_metabolites_for_taxon(name)

        metabolites = table[kn_metabolite_name_column].values.tolist()

        self.assertEqual(metabolites, known_vals)

    def test_no_info(self):
        apoc_no_info_searches = ['XXX', 'Mandevilla', 'Tromotriche', 'Orthanthera', 'Bustelma', 'Cystostemma',
                                 'Widgrenia', 'Dactylostelma', 'Gothofreda', 'Oxystelma', 'Rhombonema',
                                 'Pattalias', 'Macbridea', 'Vadulia', 'Pentacyphus', 'Pentatropis',
                                 'Acustelma']

        all_genera_df = pd.DataFrame()
        for i in tqdm(range(len(apoc_no_info_searches)), desc="Searching genera in Knapsack…", ascii=False,
                      ncols=80):
            genus = apoc_no_info_searches[i]
            genus_table = get_metabolites_for_taxon(genus)
            if len(genus_table.index) > 0:
                all_genera_df = pd.concat([all_genera_df, genus_table])
        if len(all_genera_df.index) > 0:
            acc_df = get_accepted_info_from_names_in_column(all_genera_df, 'Organism',
                                                            families_of_interest=['Apocynaceae'])
            acc_df.to_csv(os.path.join(test_output_dir, 'apoc_no_info.csv'))
            acc_df = acc_df.dropna(subset=[wcvp_accepted_columns['id']])

            self.assertEqual(len(acc_df.index), 0)

        rub_no_info = ['Thouarsiora', 'Bemsetia', 'Tsiangia', 'Schetti', 'Taligalea', 'Zuccarinia', 'Jackia',
                       'Janotia', 'Jovetia', 'Joosia', 'Gouldia', 'Neobaumannia', 'Dentillaria', 'Kohautia']

        all_genera_df = pd.DataFrame()
        for i in tqdm(range(len(rub_no_info)), desc="Searching genera in Knapsack…", ascii=False,
                      ncols=80):
            genus = rub_no_info[i]
            genus_table = get_metabolites_for_taxon(genus)
            if len(genus_table.index) > 0:
                all_genera_df = pd.concat([all_genera_df, genus_table])
        if len(all_genera_df.index) > 0:
            acc_df = get_accepted_info_from_names_in_column(all_genera_df, 'Organism',
                                                            families_of_interest=['Rubiaceae'])
            acc_df.to_csv(os.path.join(test_output_dir, 'rub_no_info.csv'))
            acc_df = acc_df.dropna(subset=[wcvp_accepted_columns['id']])

            self.assertEqual(len(acc_df.index), 0)

    def test_meta_known_taxa(self):
        known_vals = ['(+)-Aspidospermidine', '(+)-Fendlerine', 'Alalakine', 'Aspidolimidine', 'Limaspermine',
                      'N-Acetylaspidospermidine']
        self.taxon_test('Aspidosperma album', known_vals)

        # Test some synonyms with vals
        self.taxon_test('Curarea', ['Isochondodendrine', 'Isochondodendrine', 'Isochondodendrine', 'Limacine',
                                    "(-)-Limacine 2'-beta-N-oxide", '(-)-Curine', '(-)-Krukovine',
                                    "(-)-Limacine 2'-alpha-N-oxide", '(-)-Limacine, 2-beta-N-oxide',
                                    '(+)-Candicusine', 'Limacusine'])

    def test_data_for_family(self):
        # logan = get_metabolites_in_family('Loganiaceae', output_csv=os.path.join(test_output_dir,
        #                                                                          'loganiaceae_metabolites.csv'))
        logan = pd.read_csv(os.path.join(test_output_dir, 'loganiaceae_metabolites.csv'))

        lucida = logan[logan[wcvp_accepted_columns['name']] == 'Strychnos lucida'][
            kn_metabolite_name_column].values

        known_lucida_vals = ['Brucine', 'Strychnine', 'Acanthoside B', '3-O-Caffeoylquinic acid', 'Loganin',
                             'Adenosine', 'Loganate', 'Cantleyoside', 'Sylvestroside I', 'Sweroside',
                             'Tachioside', 'alpha-Colubrine', 'beta-Colubrine', 'Brucine N-oxide',
                             'Diaboline', 'Normacusine B', 'Pseudobrucine', 'Pseudostrychnine',
                             '11-Methoxydiaboline', '3,4-di-O-caffeoylquinic acid',
                             'Ligustrinoside', 'Picconioside I', 'Secoxyloganin', 'Staunoside C',
                             'Triplostoside A']

        for m in lucida:
            self.assertIn(m, known_lucida_vals, msg=m)

        for m in known_lucida_vals:
            self.assertIn(m, lucida, msg=m)

        # logan_alk_df = get_alkaloids_from_metabolites(logan, 'Metabolite', temp_output_csv=os.path.join(test_output_dir,
        #                                                                                                 'logan_metabolites_w_alks.csv'),
        #                                               output_csv=os.path.join(test_output_dir,
        #                                                                       'logan_metabolites_w_alks_final.csv'))
        #
        # alkaloid_formulae = logan_alk_df[kn_metabolite_name_column].values
        # all_formulae = logan[kn_metabolite_name_column].values
        # for alk in alkaloid_formulae:
        #     self.assertIn(alk, all_formulae)
        #
        # self.assertGreater(len(all_formulae), len(alkaloid_formulae))

    def test_all_genera_searched_for(self):

        # metas_df = get_metabolites_in_family('Rubiaceae',output_csv=os.path.join(test_output_dir, 'Rubiaceae_kn_search.csv'))
        metas_df = pd.read_csv(os.path.join(test_output_dir, 'Rubiaceae_kn_search_accepted_info.csv'))

        rub_genera = get_all_taxa(families_of_interest=['Rubiaceae'], ranks=['Genus'], accepted=True)[
            wcvp_accepted_columns['name']].values
        rub_no_info = ['Thouarsiora', 'Bemsetia', 'Tsiangia', 'Schetti', 'Taligalea', 'Zuccarinia', 'Jackia',
                       'Janotia', 'Jovetia', 'Joosia', 'Gouldia', 'Neobaumannia', 'Dentillaria', 'Kohautia', 'Wittmackanthus', 'Chaetostachydium',
                       'Schumanniophyton',
                       'Jackiopsis',
                       'Neohymenopogon',
                       'Martensianthus',
                       'Ferdinandusa',
                       'Coccochondra',
                       'Denscantia',
                       'Sacosperma',
                       'Nostolachma',
                       'Virectaria',
                       'Pleiocoryne',
                       'Mericarpaea',
                       'Macrosphyra',
                       'Macrocnemum',
                       'Jamaicanthus',
                       'Agathisanthemum',
                       'Carpacoce',
                       'Calycosia',
                       'Condaminea',
                       'Conostomium',
                       'Didymosalpinx',
                       'Siemensia',
                       'Robbrechtia',
                       'Calochone',
                       'Ditrichanthus',
                       'Mexotis',
                       'Argocoffeopsis',
                       'Houstonia',
                       'Deccania',
                       'Diacrodon',
                       'Kutchubaea',
                       'Stichianthus',
                       'Tangshuia',
                       'Stenosepala',
                       'Euclinia',
                       'Durringtonia',
                       'Pagamea',
                       'Sherbournia',
                       'Urophyllum',
                       'Fadogiella',
                       'Macbrideina',
                       '× Galiasperula',
                       'Gardeniopsis',
                       'Heterophyllaea',
                       'Keetia',
                       'Pagameopsis',
                       'Ceriscoides',
                       'Dialypetalanthus',
                       'Luculia',
                       'Chamaepentas',
                       'Valantia',
                       'Pseudohamelia',
                       'Bertiera',
                       'Diyaminauclea',
                       'Fergusonia',
                       'Hutchinsonia',
                       'Kadua',
                       'Mantalania',
                       'Neanotis',
                       'Melanopsidium',
                       'Landiopsis',
                       'Appunia',
                       'Phellocalyx',
                       'Carajasia',
                       'Alibertia',
                       'Atractogyne',
                       'Hyperacanthus',
                       'Ottoschmidtia',
                       'Tapanhuacanga',
                       'Triflorensia',
                       'Tricalysia',
                       'Antherostele',
                       'Dendrosipanea',
                       'Lemyrea',
                       'Riodocea',
                       'Shaolinchiana',
                       'Trichostachys',
                       'Diodia',
                       'Remijia',
                       'Dolianthus',
                       'Globulostylis',
                       'Gonzalagunia',
                       'Otiophora',
                       'Pitardella',
                       'Bremeria',
                       'Omiltemia',
                       'Boholia',
                       'Bothriospora',
                       'Raritebe',
                       'Brenania',
                       'Cyanoneuron',
                       'Squamellaria',
                       'Acrosynanthus',
                       'Planaltina',
                       'Edrastima',
                       'Paranotis',
                       'Morelia',
                       'Glossostipula',
                       'Coryphothamnus',
                       'Stephanococcus',
                       'Didymopogon',
                       'Schmidtottia',
                       'Achilleanthus',
                       'Myrmephytum',
                       'Rennellia',
                       'Micrasepalum',
                       'Crossopteryx',
                       'Rovaeanthus',
                       'Rhodopentas',
                       'Canephora',
                       'Cephalanthus',
                       'Warszewiczia',
                       'Machaonia',
                       'Mussaendopsis',
                       'Platycarpum',
                       'Ridsdalea',
                       'Hexaphylla',
                       'Malanea',
                       'Vidalasia',
                       'Amaioua',
                       'Emmeorhiza',
                       'Eriosemopsis',
                       'Pseudodiplospora',
                       'Calycosiphonia',
                       'Nichallea',
                       'Aleisanthia',
                       'Antirhea',
                       'Phuopsis',
                       'Puffia',
                       'Phialiphora',
                       'Polysphaeria',
                       'Pubistylus',
                       'Molopanthera',
                       'Dolichometra',
                       'Pentanisia',
                       'Perakanthus',
                       'Spermadictyon',
                       'Sommera',
                       'Multidentia',
                       'Hekistocarpa',
                       'Maguireothamnus',
                       'Diadorimia',
                       'Chomelia',
                       'Coutaportla',
                       'Guihaiothamnus',
                       'Adolphoduckea',
                       'Canthiumera',
                       'Dibridsonia',
                       'Rytigynia',
                       'Pentodon',
                       'Gomphocalyx',
                       'Pentaloncha',
                       'Pentanopsis',
                       'Petitiocodon',
                       'Tocoyena',
                       'Xanthophytum',
                       'Saldinia',
                       'Parachimarrhis',
                       'Batopedina',
                       'Carphalea',
                       'Neoblakea',
                       'Paracarphalea',
                       'Lepidostoma',
                       'Anthospermum',
                       'Homollea',
                       'Robynsia',
                       'Tarennella',
                       'Cubanola',
                       'Coptosapelta',
                       'Galopina',
                       'Oligocodon',
                       'Schizocalyx',
                       'Ramonadoxa',
                       'Hymenocoleus',
                       'Phyllis',
                       'Pinckneya',
                       'Agouticarpa',
                       'Nargedia',
                       'Gyrostipula',
                       'Hedstromia',
                       'Hindsia',
                       'Lecananthus',
                       'Schradera',
                       'Perama',
                       'Atractocarpus',
                       'Cyclophyllum',
                       'Ernodea',
                       'Pittoniotis',
                       'Strumpfia',
                       'Nematostylis',
                       'Hippotis',
                       'Rachicallis',
                       'Rhaphidura',
                       'Emmenopterys',
                       'Eosanthe',
                       'Oldenlandiopsis',
                       'Tessiera',
                       'Alleizettella',
                       'Afrocanthium',
                       'Pseudomiltemia',
                       'Polyura',
                       'Etericius',
                       'Kraussia',
                       'Lathraeocarpa',
                       'Rondeletia',
                       'Staelia',
                       'Steyermarkia',
                       'Tobagoa',
                       'Brachytome',
                       'Colletoecema',
                       'Schizomussaenda',
                       'Rustia',
                       'Phyllopentas',
                       'Aleisanthiopsis',
                       'Pinarophyllon',
                       'Thiollierea',
                       'Hydrophylax',
                       'Craterispermum',
                       'Crobylanthe',
                       'Helictosperma',
                       'Dolichocarpa',
                       'Casasia',
                       'Clarkella',
                       'Elaeagia',
                       'Leptomischus',
                       'Pouchetia',
                       'Anthorrhiza',
                       'Kochummenia',
                       'Normandia',
                       'Duperrea',
                       'Chalepophyllum',
                       'Phialanthus',
                       'Melanoxerus',
                       'Tainus',
                       'Solenandra',
                       'Paracephaelis',
                       'Otomeria',
                       'Hyptianthera',
                       'Sabicea',
                       'Argostemma',
                       'Berghesia',
                       'Eleuthranthes',
                       'Heinsia',
                       'Scyphiphora',
                       'Arachnothryx',
                       'Aitchisonia',
                       'Nodocarpaea',
                       'Peponidium',
                       'Lucya',
                       'Schizenterospermum',
                       'Paragenipa',
                       'Arcytophyllum',
                       'Fosbergia',
                       'Gleasonia',
                       'Octotropis',
                       'Oxyanthus',
                       'Wendlandia',
                       'Stenotis',
                       'Ladenbergia',
                       'Lelya',
                       'Thliphthisa',
                       'Tournefortiopsis',
                       'Aidiopsis',
                       'Airosperma',
                       'Callipeltis',
                       'Opercularia',
                       'Pseudomussaenda',
                       'Asperula',
                       'Bungarimba',
                       'Phyllomelia',
                       'Astiella',
                       'Gaertnera',
                       'Leptoscela',
                       'Manettia',
                       'Morindopsis',
                       'Bullockia',
                       'Cowiea',
                       'Dibrachionostylus',
                       'Microphysa',
                       'Roigella',
                       'Stevensia',
                       'Stipularia',
                       'Steenisia',
                       'Acunaeanthus',
                       'Empogona',
                       'Cynanchica',
                       'Pseudopyxis',
                       'Henriquezia',
                       'Crusea',
                       'Flagenium',
                       'Greeniopsis',
                       'Hypobathrum',
                       'Pimentelia',
                       'Siphonandrium',
                       'Schwendenera',
                       'Nernstia',
                       'Amphiasma',
                       'Badusa',
                       'Holstianthus',
                       'Lintersemina',
                       'Alseis',
                       'Dioicodendron',
                       'Declieuxia',
                       'Dentella',
                       'Portlandia',
                       'Temnocalyx',
                       'Pseudogalium',
                       'Aulacocalyx',
                       'Benkara',
                       'Coelopyrena',
                       'Leptodermis',
                       'Neomussaenda',
                       'Habroneuron',
                       'Khasiaclunea',
                       'Larsenaikia',
                       'Oxyceros',
                       'Riqueuria',
                       'Syringantha',
                       'Involucrella',
                       'Paraknoxia',
                       'Acranthera',
                       'Bobea',
                       'Mouretia',
                       'Cinchonopsis',
                       'Bouvardia',
                       'Neblinathamnus',
                       'Neobertiera',
                       'Hexasepalum',
                       'Catesbaea',
                       'Cremaspora',
                       'Standleya',
                       'Picardaea',
                       'Adenorandia',
                       'Ceratopyxis',
                       'Cladoceras',
                       'Dolichodelphys',
                       'Duidania',
                       'Tennantia',
                       'Lecariocalyx',
                       'Stilpnophyllum',
                       'Buchozia',
                       'Tamilnadia',
                       'Triainolepis',
                       'Coccocypselum',
                       'Coptosperma',
                       'Shaferocharis',
                       'Bikkia',
                       'Didymaea',
                       'Payera',
                       'Flexanthera',
                       'Patima',
                       'Exallosperma',
                       'Kindia',
                       'Didymochlamys',
                       'Massularia',
                       'Merumea',
                       'Donnellyanthus',
                       'Wandersong',
                       'Benzonia',
                       'Eizia',
                       'Gillespiea',
                       'Kajewskiella',
                       'Mitracarpus',
                       'Sericanthe',
                       'Pomax',
                       'Rutidea',
                       'Tortuella',
                       'Richardia',
                       'Chione',
                       'Mazaea',
                       'Vangueria',
                       'Ronabea',
                       'Aoranthe',
                       'Cuviera',
                       'Dolicholobium',
                       'Hydnophytum',
                       'Lamprothamnus',
                       'Plocaniophyllon',
                       'Suberanthus',
                       'Cosmibuena',
                       'Carterella',
                       'Temnopteryx',
                       'Theligonum',
                       'Tulearia',
                       'Maschalodesme',
                       'Mastixiodendron',
                       'Pseudaidia',
                       'Vangueriopsis',
                       'Seychellea',
                       'Kupeantha',
                       'Ludekia',
                       'Pygmaeothamnus',
                       'Kanapia',
                       'Retiniphyllum',
                       'Coptophyllum',
                       'Schismatoclada',
                       'Bridsonia',
                       'Tamridaea',
                       'Hodgkinsonia',
                       'Rogiera',
                       'Villaria',
                       'Salzmannia',
                       'Schizocolea',
                       'Fadogia',
                       'Motleyothamnus',
                       'Peripeplus',
                       'Preussiodora',
                       'Sphinctanthus',
                       'Xantonneopsis',
                       'Paracorynanthe',
                       'Discospermum',
                       'Kailarsenia',
                       'Maguireocharis',
                       'Manostachya',
                       'Galiniera',
                       'Vangueriella',
                       'Trailliaedoxa',
                       'Chapelieria',
                       'Streblosiopsis',
                       'Pseudocoptosperma',
                       'Anthospermopsis',
                       'Himalrandia',
                       'Erithalis',
                       'Foonchewia',
                       'Stylosiphonia',
                       'Stenaria',
                       'Balmea',
                       'Myrmecodia',
                       'Myrmeconauclea',
                       'Tromlyca',
                       'Klossia',
                       'Blepharidium',
                       'Notopleura',
                       'Geophila',
                       'Amphidasya',
                       'Paralasianthus',
                       'Kerianthera',
                       'Mitriostigma',
                       'Osa',
                       'Parapentas',
                       'Tarennoidea',
                       'Randia',
                       'Gallienia',
                       'Glionnetia',
                       'Acrobotrys',
                       'Bradea',
                       'Danais',
                       'Meyna',
                       'Rhadinopus',
                       'Coutareopsis',
                       'Cosmocalyx',
                       'Synaptantha',
                       'Amphistemon',
                       'Phylohydrax',
                       'Oreopolus',
                       'Dirichletia',
                       'Limnosipanea',
                       'Nertera',
                       'Neurocalyx',
                       'Razafimandimbisonia',
                       'Belonophora',
                       'Capirona',
                       'Hedythyrsus',
                       'Hillia',
                       'Ochreinauclea',
                       'Nenax',
                       'Kelloggia',
                       'Botryarrhena',
                       'Pteridocalyx',
                       'Aphanocarpus',
                       'Augusta',
                       'Byrsophyllum',
                       'Cruckshanksia',
                       'Fernelia',
                       'Pachystylus',
                       'Placocarpa',
                       'Galianthe',
                       'Pseudonesohedyotis',
                       'Lerchea',
                       'Phyllocrater',
                       'Ramosmania',
                       'Scolosanthus',
                       'Nesohedyotis',
                       'Streblosa',
                       'Crucianella',
                       'Mitrasacmopsis',
                       'Scyphostachys',
                       'Leucocodon',
                       'Sipaneopsis',
                       'Pentas',
                       'Ganguelia',
                       'Isidorea',
                       'Amaracarpus',
                       'Cordylostigma',
                       'Parainvolucrella',
                       'Heinsenia',
                       'Rubovietnamia',
                       'Tammsia',
                       'Dichilanthe',
                       'Thamnoldenlandia',
                       'Paganuccia',
                       'Pseudomantalania',
                       'Pyrostria',
                       'Stachyarrhena',
                       'Thogsennia',
                       'Monosalpinx',
                       'Coddia',
                       'Leucolophus',
                       'Sipanea',
                       'Praravinia',
                       'Greenea',
                       'Everistia']

        for genus in rub_genera:
            if genus not in rub_no_info:
                self.assertIn(genus, metas_df['accepted_parent'].values)
                # if genus not in metas_df['accepted_parent'].values:
                #     print(genus)


if __name__ == '__main__':
    unittest.main()
